# Generated by Django 4.1.5 on 2023-02-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AddMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, unique=True)),
                ("email", models.EmailField(blank=True, max_length=255, unique=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=16, unique=True),
                ),
                ("home_address", models.CharField(blank=True, max_length=100)),
                ("digital_address", models.CharField(blank=True, max_length=100)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Announcements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CheckInToday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_checked_in", models.BooleanField(default=False)),
                ("time_checked_in", models.TimeField(auto_now_add=True)),
                ("date_checked_in", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_title", models.CharField(max_length=255)),
                ("event_time", models.CharField(blank=True, max_length=20)),
                ("event_date", models.CharField(blank=True, max_length=20)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MorningDevotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("quotations", models.TextField()),
                ("message", models.TextField()),
                ("date_created", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("notification_title", models.CharField(blank=True, max_length=255)),
                ("notification_message", models.TextField(blank=True)),
                (
                    "read",
                    models.CharField(
                        choices=[("Read", "Read"), ("Not Read", "Not Read")],
                        default="Not Read",
                        max_length=20,
                    ),
                ),
                (
                    "notification_trigger",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Triggered", "Triggered"),
                            ("Not Triggered", "Not Triggered"),
                        ],
                        default="Triggered",
                        max_length=255,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
