# Generated by Django 4.1.5 on 2023-01-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addmember",
            name="email",
            field=models.EmailField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="addmember",
            name="name",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="addmember",
            name="phone_number",
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
    ]
